apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-app
  template:
    metadata:
      labels:
        app: poc-app
    spec:
      containers:
        - name: poc-app
          image: saksuriyas/youtube:latest
          ports:
            - containerPort: 3000  # Your Node.js application should listen on port 3000

---

apiVersion: v1
kind: Service
metadata:
  name: poc-app-service
spec:
  selector:
    app: poc-app
  ports:
    - protocol: TCP
      port: 80  # You can use port 80 here for HTTP traffic
      targetPort: 3000  # This should match the port your Node.js application is running on (3000)
  type: NodePort
